# Generated by Django 4.2.19 on 2025-02-20 12:32

from django.conf import settings
from django.db import migrations


def create_user_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    internal_user_group = Group.objects.create(name=settings.INTERNAL_USER_GROUP_NAME)
    public_user_group = Group.objects.create(name=settings.PUBLIC_USER_GROUP_NAME)
    admin_user_group = Group.objects.create(name=settings.ADMIN_USER_GROUP_NAME)

    User = apps.get_model("auth", "User")
    # give all public users the public user group
    for user in User.objects.filter(username__startswith="urn:fdc:gov.uk"):
        user.groups.add(public_user_group)

    # give all internal users the internal user group
    for user in User.objects.filter(username__endswith="id.trade.gov.uk"):
        user.groups.add(internal_user_group)

    # give all staff users (currently user management users) access to the admin user group
    for user in User.objects.filter(is_staff=True):
        user.groups.add(admin_user_group)


def delete_user_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name=settings.INTERNAL_USER_GROUP_NAME).delete()
    Group.objects.get(name=settings.PUBLIC_USER_GROUP_NAME).delete()
    Group.objects.get(name=settings.ADMIN_USER_GROUP_NAME).delete()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(create_user_groups, delete_user_groups)]
