version: "3.8"
services:
    db:
        image: postgres:16.3
        volumes:
            - ./pgdata/:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - "25432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 2s
            timeout: 6s
            retries: 5

    localstack:
        image: localstack/localstack
        ports:
          - "24566:4566"
        volumes:
          - ./aws:/etc/localstack/init/ready.d
          - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
          - S3_SKIP_SIGNATURE_VALIDATION=1

    mock-sso:
        image: ukti/mock-sso
        ports:
         - 28080:8080
        environment:
          - MOCK_SSO_TOKEN=dummy-token
          - MOCK_SSO_SCOPE=read
          - MOCK_SSO_USERNAME=testuser
          - MOCK_SSO_EMAIL_USER_ID=testuser@example.com
          - MOCK_SSO_VALIDATE_TOKEN

    redis:
      image: redis
      ports:
        - "26379:6379"

    mock-one-login:
      build:
          context: ./mock_one_login
          dockerfile: Dockerfile
      ports:
          - "28081:9090"
      environment:
        - PORT=9090
        - HOST=localhost
        - CLIENT_ID=my-client
        - CLIENT_SECRET=my-secret
        - CLIENT_REDIRECT_URI=http://apply-for-a-licence:{port}/authentication/callback/
        - DJANGO_SERVER_PORT=8000
        - CLIENT_LOGOUT_REDIRECT_URI=http://localhost:8080
        # uncomment the following line to enable debug logging
        # - DEBUG=oidc-provider:*
