# Generated by Django 4.2.13 on 2024-06-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmailVerification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("email_verification_code", models.CharField(max_length=6)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("verified", models.BooleanField(default=False)),
                ("user_session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sessions.session")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "who_do_you_want_the_licence_to_cover",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business", "A business or several businesses"),
                            ("individual", "A named individual or several named individuals"),
                            ("myself", "Myself"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("user_email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("your_details_full_name", models.CharField(max_length=255)),
                (
                    "your_details_name_of_business_you_work_for",
                    models.CharField(max_length=300, verbose_name="Business you work for"),
                ),
                ("your_details_role", models.CharField(max_length=255)),
                ("held_previous_licence", models.CharField(choices=[("yes", "Yes"), ("no", "No")], max_length=11)),
                ("previous_licences", models.TextField(blank=True, null=True)),
                (
                    "user_email_verification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apply_for_a_licence.useremailverification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalUserEmailVerification",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("email_verification_code", models.CharField(max_length=6)),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("verified", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sessions.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user email verification",
                "verbose_name_plural": "historical user email verifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLicence",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "who_do_you_want_the_licence_to_cover",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business", "A business or several businesses"),
                            ("individual", "A named individual or several named individuals"),
                            ("myself", "Myself"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("user_email_address", models.EmailField(blank=True, max_length=254, null=True)),
                ("your_details_full_name", models.CharField(max_length=255)),
                (
                    "your_details_name_of_business_you_work_for",
                    models.CharField(max_length=300, verbose_name="Business you work for"),
                ),
                ("your_details_role", models.CharField(max_length=255)),
                ("held_previous_licence", models.CharField(choices=[("yes", "Yes"), ("no", "No")], max_length=11)),
                ("previous_licences", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user_email_verification",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apply_for_a_licence.useremailverification",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical licence",
                "verbose_name_plural": "historical licences",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
