# Generated by Django 4.2.14 on 2024-07-31 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apply_for_a_licence", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="address_line_3",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="address_line_4",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="county",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="town_or_city",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="address_line_3",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="address_line_4",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="county",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="town_or_city",
        ),
        migrations.CreateModel(
            name="HistoricalAddress",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("address_line_1", models.CharField(max_length=200)),
                ("address_line_2", models.CharField(blank=True, max_length=200, null=True)),
                ("address_line_3", models.CharField(blank=True, max_length=200, null=True)),
                ("address_line_4", models.CharField(blank=True, max_length=200, null=True)),
                ("postcode", models.CharField(max_length=20)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("town_or_city", models.CharField(max_length=250)),
                ("county", models.CharField(blank=True, max_length=250, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apply_for_a_licence.applicant",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "historical address",
                "verbose_name_plural": "historical addresss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("address_line_1", models.CharField(max_length=200)),
                ("address_line_2", models.CharField(blank=True, max_length=200, null=True)),
                ("address_line_3", models.CharField(blank=True, max_length=200, null=True)),
                ("address_line_4", models.CharField(blank=True, max_length=200, null=True)),
                ("postcode", models.CharField(max_length=20)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("town_or_city", models.CharField(max_length=250)),
                ("county", models.CharField(blank=True, max_length=250, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="apply_for_a_licence.applicant"
                    ),
                ),
            ],
            options={
                "db_table": "address",
                "db_table_comment": "The address has a start and end date.  the constraint manages those. ",
            },
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apply_for_a_licence.address",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="apply_for_a_licence.address"
            ),
        ),
    ]
