# Generated by Django 4.2.14 on 2024-08-08 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseapplication",
            name="regime",
        ),
        migrations.RemoveField(
            model_name="historicalbaseapplication",
            name="regime",
        ),
        migrations.AddField(
            model_name="baseapplication",
            name="regimes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="historicalbaseapplication",
            name="regimes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalRegime",
        ),
        migrations.DeleteModel(
            name="Regime",
        ),
    ]
