# Generated by Django 4.2.14 on 2024-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisation",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], max_length=3, null=True),
        ),
    ]
