# Generated by Django 4.2.15 on 2024-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallicence",
            name="who_do_you_want_the_licence_to_cover",
            field=models.CharField(
                choices=[
                    ("business", "A business or businesses with a UK nexus"),
                    ("individual", "Named individuals with a UK nexus working for a business with no UK nexus"),
                    ("myself", "Myself"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="licence",
            name="who_do_you_want_the_licence_to_cover",
            field=models.CharField(
                choices=[
                    ("business", "A business or businesses with a UK nexus"),
                    ("individual", "Named individuals with a UK nexus working for a business with no UK nexus"),
                    ("myself", "Myself"),
                ],
                max_length=255,
            ),
        ),
    ]
