# Generated by Django 4.2.13 on 2024-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservices",
            name="service_activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="services",
            name="service_activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalregime",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalregime",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regime",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regime",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
