# Generated by Django 4.2.13 on 2024-06-26 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0002_historicallicence_user_email_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicence",
            name="held_previous_licence",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="previous_licences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="your_details_full_name",
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="your_details_name_of_business_you_work_for",
            field=models.CharField(default="role", max_length=300, verbose_name="Business you work for"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="your_details_role",
            field=models.CharField(default="role", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="held_previous_licence",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], default=False, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="previous_licences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="your_details_full_name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="your_details_name_of_business_you_work_for",
            field=models.CharField(default="bus", max_length=300, verbose_name="Business you work for"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="your_details_role",
            field=models.CharField(default="role", max_length=255),
            preserve_default=False,
        ),
    ]
