# Generated by Django 4.2.14 on 2024-08-13 11:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0002_remove_baseapplication_regime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalindividual",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="address_line_4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="county",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="town_or_city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="address_line_4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="county",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="town_or_city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="applicationtype",
            name="who_do_you_want_the_licence_to_cover",
            field=models.CharField(
                choices=[
                    ("business", "A business or several businesses"),
                    ("individual", "A named individual or several named individuals"),
                    ("myself", "Myself"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicationtype",
            name="who_do_you_want_the_licence_to_cover",
            field=models.CharField(
                choices=[
                    ("business", "A business or several businesses"),
                    ("individual", "A named individual or several named individuals"),
                    ("myself", "Myself"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
