# Generated by Django 4.2.13 on 2024-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0002_historicalservices_service_activities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalregime",
            name="licences_guid_flag",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalregime",
            name="shown_gui_flag",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regime",
            name="licences_guid_flag",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regime",
            name="shown_gui_flag",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
