# Generated by Django 4.2.14 on 2024-07-31 07:57

from django.db import migrations, models
import django.db.models.deletion
import django_chunk_upload_handlers.clam_av
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0002_remove_historicalorganisation_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaladdress",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="historicaladdress",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="address",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="", validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result]
            ),
        ),
        migrations.AddField(
            model_name="ground",
            name="licensing_grounds",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "civil_society",
                        "Civil society activities that directly promote democracy, human rights or the rule of law in Russia",
                    ),
                    ("energy", "Services necessary for ensuring critical energy supply to any country"),
                    (
                        "divest",
                        "Services necessary for non - Russian persons to divest from Russia, or to wind down business operations in Russia",
                    ),
                    ("humanitarian", "The delivery of humanitarian assistance activity"),
                    (
                        "parent_or_subsidiary_company",
                        "Services to a person connected with Russia by a UK parent company or UK subsidiary of that parent company",
                    ),
                    (
                        "medical_and_pharmaceutical",
                        "Medical and pharmaceutical purposes for the benefit of the civilian population",
                    ),
                    (
                        "safety",
                        "Services required to enable activities necessary for the urgent prevention or mitigation of an event likely to have a serious and significant impact on human health or safety, including the safety of existing infrastructure, or the environment",
                    ),
                    (
                        "food",
                        "Services in connection with the production or distribution of food for the benefit of the civilian population",
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result],
            ),
        ),
        migrations.AddField(
            model_name="historicalground",
            name="licensing_grounds",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "civil_society",
                        "Civil society activities that directly promote democracy, human rights or the rule of law in Russia",
                    ),
                    ("energy", "Services necessary for ensuring critical energy supply to any country"),
                    (
                        "divest",
                        "Services necessary for non - Russian persons to divest from Russia, or to wind down business operations in Russia",
                    ),
                    ("humanitarian", "The delivery of humanitarian assistance activity"),
                    (
                        "parent_or_subsidiary_company",
                        "Services to a person connected with Russia by a UK parent company or UK subsidiary of that parent company",
                    ),
                    (
                        "medical_and_pharmaceutical",
                        "Medical and pharmaceutical purposes for the benefit of the civilian population",
                    ),
                    (
                        "safety",
                        "Services required to enable activities necessary for the urgent prevention or mitigation of an event likely to have a serious and significant impact on human health or safety, including the safety of existing infrastructure, or the environment",
                    ),
                    (
                        "food",
                        "Services in connection with the production or distribution of food for the benefit of the civilian population",
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="address_line_4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apply_for_a_licence.applicant",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="county",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="town_or_city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address_line_4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="applicant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="apply_for_a_licence.applicant"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="county",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="town_or_city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="HistoricalAddress",
        ),
    ]
