# Generated by Django 4.2.13 on 2024-06-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apply_for_a_licence", "0002_historicallicence_user_email_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Individual",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                (
                    "nationality_and_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uk_national_uk_location", "UK national located in the UK"),
                            ("uk_national_non_uk_location", "UK national located outside the UK"),
                            ("dual_national_uk_location", "Dual national (includes UK) located in the UK"),
                            ("dual_national_non_uk_location", "Dual national (includes UK) located outside the UK"),
                            ("non_uk_national_uk_location", "Non-UK national located in the UK"),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="your_details_full_name",
            field=models.CharField(default="John", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="your_details_name_of_business_you_work_for",
            field=models.CharField(default="DBT", max_length=300, verbose_name="Business you work for"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="your_details_role",
            field=models.CharField(default="role", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="your_details_full_name",
            field=models.CharField(default="John smith", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="your_details_name_of_business_you_work_for",
            field=models.CharField(default="DBT", max_length=300, verbose_name="Business you work for"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licence",
            name="your_details_role",
            field=models.CharField(default="Role", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HistoricalIndividual",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                (
                    "nationality_and_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("uk_national_uk_location", "UK national located in the UK"),
                            ("uk_national_non_uk_location", "UK national located outside the UK"),
                            ("dual_national_uk_location", "Dual national (includes UK) located in the UK"),
                            ("dual_national_non_uk_location", "Dual national (includes UK) located outside the UK"),
                            ("non_uk_national_uk_location", "Non-UK national located in the UK"),
                        ],
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "historical individual",
                "verbose_name_plural": "historical individuals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBusiness",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.TextField()),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(blank=True, null=True)),
                ("address_line_3", models.TextField(blank=True, null=True)),
                ("address_line_4", models.TextField(blank=True, null=True)),
                ("town_or_city", models.TextField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("county", models.TextField(blank=True, null=True)),
                ("postal_code", models.TextField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apply_for_a_licence.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical business",
                "verbose_name_plural": "historical businesss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(blank=True, null=True)),
                ("address_line_3", models.TextField(blank=True, null=True)),
                ("address_line_4", models.TextField(blank=True, null=True)),
                ("town_or_city", models.TextField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("county", models.TextField(blank=True, null=True)),
                ("postal_code", models.TextField()),
                ("licence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="apply_for_a_licence.licence")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
