# Generated by Django 4.2.13 on 2024-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0003_individual_historicallicence_your_details_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalindividual",
            name="first_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalindividual",
            name="last_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="individual",
            name="first_name",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="individual",
            name="last_name",
            field=models.TextField(max_length=255),
        ),
    ]
