# Generated by Django 4.2.15 on 2024-09-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0003_alter_historicallicence_licensing_grounds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallicence",
            name="type_of_service",
            field=models.CharField(
                choices=[
                    ("professional_and_business", "Professional and business services (Russia)"),
                    ("energy_related", "Energy-related services (Russia)"),
                    (
                        "infrastructure_or_tourism_related",
                        "Infrastructure or tourism-related services to non-government controlled Ukrainian territories (Russia)",
                    ),
                    (
                        "interception_or_monitoring",
                        "Interception or monitoring services (Russia, Belarus, Iran, Myanmar, Syria and Venezuela)",
                    ),
                    (
                        "mining_manufacturing_or_computer",
                        "Mining, manufacturing or computer services (Democratic People’s Republic of Korea)",
                    ),
                    ("ships_or_aircraft_related", "Ships or aircraft-related services (Democratic People's Republic of Korea)"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="licence",
            name="type_of_service",
            field=models.CharField(
                choices=[
                    ("professional_and_business", "Professional and business services (Russia)"),
                    ("energy_related", "Energy-related services (Russia)"),
                    (
                        "infrastructure_or_tourism_related",
                        "Infrastructure or tourism-related services to non-government controlled Ukrainian territories (Russia)",
                    ),
                    (
                        "interception_or_monitoring",
                        "Interception or monitoring services (Russia, Belarus, Iran, Myanmar, Syria and Venezuela)",
                    ),
                    (
                        "mining_manufacturing_or_computer",
                        "Mining, manufacturing or computer services (Democratic People’s Republic of Korea)",
                    ),
                    ("ships_or_aircraft_related", "Ships or aircraft-related services (Democratic People's Republic of Korea)"),
                ]
            ),
        ),
    ]
