# Generated by Django 4.2.13 on 2024-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0004_alter_historicalindividual_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalindividual",
            name="nationality_and_location",
            field=models.CharField(
                choices=[
                    ("uk_national_uk_location", "UK national located in the UK"),
                    ("uk_national_non_uk_location", "UK national located outside the UK"),
                    ("dual_national_uk_location", "Dual national (includes UK) located in the UK"),
                    ("dual_national_non_uk_location", "Dual national (includes UK) located outside the UK"),
                    ("non_uk_national_uk_location", "Non-UK national located in the UK"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="nationality_and_location",
            field=models.CharField(
                choices=[
                    ("uk_national_uk_location", "UK national located in the UK"),
                    ("uk_national_non_uk_location", "UK national located outside the UK"),
                    ("dual_national_uk_location", "Dual national (includes UK) located in the UK"),
                    ("dual_national_non_uk_location", "Dual national (includes UK) located outside the UK"),
                    ("non_uk_national_uk_location", "Non-UK national located in the UK"),
                ]
            ),
        ),
    ]
