# Generated by Django 4.2.16 on 2024-10-18 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0005_alter_document_file_alter_historicaldocument_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallicence",
            name="professional_or_business_service",
        ),
        migrations.RemoveField(
            model_name="licence",
            name="professional_or_business_service",
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="professional_or_business_services",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("accounting", "Accounting"),
                        ("advertising", "Advertising"),
                        ("architectural", "Architectural"),
                        ("auditing", "Auditing"),
                        ("business_and_management_consulting", "Business and management consulting"),
                        ("engineering", "Engineering"),
                        ("it_consultancy_and_design", "IT consultancy and design"),
                        ("legal_advisory", "Legal advisory"),
                        ("public_relations", "Public relations"),
                    ]
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="licence",
            name="professional_or_business_services",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("accounting", "Accounting"),
                        ("advertising", "Advertising"),
                        ("architectural", "Architectural"),
                        ("auditing", "Auditing"),
                        ("business_and_management_consulting", "Business and management consulting"),
                        ("engineering", "Engineering"),
                        ("it_consultancy_and_design", "IT consultancy and design"),
                        ("legal_advisory", "Legal advisory"),
                        ("public_relations", "Public relations"),
                    ]
                ),
                null=True,
                size=None,
            ),
        ),
    ]
