# Generated by Django 4.2.14 on 2024-10-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0006_remove_historicallicence_professional_or_business_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallicence",
            name="professional_or_business_services",
        ),
        migrations.RemoveField(
            model_name="licence",
            name="professional_or_business_services",
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="professional_or_business_service",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="professional_or_business_service",
            field=models.CharField(blank=True, null=True),
        ),
    ]
