# Generated by Django 4.2.18 on 2025-03-28 11:27

import apply_for_a_licence.utils
import core.document_storage
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apply_for_a_licence", "0008_historicallicence_user_licence_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useremailverification",
            name="user_session",
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="historicallicence",
            name="user_email_verification",
        ),
        migrations.RemoveField(
            model_name="licence",
            name="user_email_verification",
        ),
        migrations.AddField(
            model_name="document",
            name="original_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="original_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="is_applicant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="submitter_reference",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="business_registered_on_companies_house",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")], max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="is_applicant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="individual",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="individual",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="licence",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="submitter_reference",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="business_registered_on_companies_house",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")], max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="organisation",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=340,
                null=True,
                storage=core.document_storage.PermanentDocumentStorage(),
                upload_to=apply_for_a_licence.utils.get_file_s3_key,
            ),
        ),
        migrations.AlterField(
            model_name="historicallicence",
            name="regimes",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name="historicallicence",
            name="service_activities",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="relationship_provider",
            field=models.TextField(db_comment="what is the relationship between the provider and the recipient?", null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="regimes",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name="licence",
            name="service_activities",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licence_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="relationship_provider",
            field=models.TextField(db_comment="what is the relationship between the provider and the recipient?", null=True),
        ),
        migrations.DeleteModel(
            name="HistoricalUserEmailVerification",
        ),
        migrations.DeleteModel(
            name="UserEmailVerification",
        ),
    ]
