# Generated by Django 4.2.17 on 2025-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0009_historicallicence_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicence",
            name="submitter_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="submitter_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
