# Generated by Django 4.2.20 on 2025-04-09 12:44

from django.db import migrations
import uuid


def complete_licence(apps, schema_editor):
    Licence = apps.get_model("apply_for_a_licence", "Licence")
    for licence in Licence.objects.all():
        if licence.reference and not licence.status:
            licence.status = "submitted"
        licence.save()


def complete_organisation(apps, schema_editor):
    Organisation = apps.get_model("apply_for_a_licence", "Organisation")
    for organisation in Organisation.objects.all():
        if not organisation.licence.status and organisation.licence.reference:
            organisation.status = "complete"
        organisation.save()


def complete_individual(apps, schema_editor):
    Individual = apps.get_model("apply_for_a_licence", "Individual")
    for individual in Individual.objects.all():
        if not individual.licence.status and individual.licence.reference:
            individual.status = "complete"
            individual.save()


def reverse_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0009_remove_useremailverification_user_session_and_more"),
    ]

    operations = [
        migrations.RunPython(complete_organisation, reverse_function),
        migrations.RunPython(complete_individual, reverse_function),
        migrations.RunPython(complete_licence, reverse_function),
    ]
