# Generated by Django 4.2.20 on 2025-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0010_data_migration_licence_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicence",
            name="do_you_want_to_add_another_business",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="do_you_want_to_add_another_individual",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="historicallicence",
            name="do_you_want_to_add_another_recipient",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="do_you_want_to_add_another_business",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="do_you_want_to_add_another_individual",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="licence",
            name="do_you_want_to_add_another_recipient",
            field=models.BooleanField(null=True),
        ),
    ]
