# Generated by Django 4.2.18 on 2025-01-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "apply_for_a_licence",
            "0009_historicallicence_status_and_more_squashed_0010_historicallicence_submitter_reference_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useremailverification",
            name="user_session",
        ),
        migrations.RemoveField(
            model_name="historicallicence",
            name="user_email_verification",
        ),
        migrations.RemoveField(
            model_name="licence",
            name="user_email_verification",
        ),
        migrations.DeleteModel(
            name="HistoricalUserEmailVerification",
        ),
        migrations.DeleteModel(
            name="UserEmailVerification",
        ),
    ]
