# Generated by Django 4.2.18 on 2025-01-29 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0011_remove_useremailverification_user_session_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="historicalindividual",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="business_registered_on_companies_house",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")], max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="individual",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="business_registered_on_companies_house",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")], max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(blank=True, choices=[("yes", "Yes"), ("no", "No")], null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(blank=True, choices=[("yes", "Yes"), ("no", "No")], null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
