# Generated by Django 4.2.20 on 2025-05-09 09:55

import apply_for_a_licence.utils
import core.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0011_historicallicence_do_you_want_to_add_another_business_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="temp_file",
            field=models.FileField(
                blank=True,
                max_length=340,
                null=True,
                storage=core.document_storage.TemporaryDocumentStorage(),
                upload_to=apply_for_a_licence.utils.get_file_s3_key,
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="temp_file",
            field=models.TextField(blank=True, max_length=340, null=True),
        ),
    ]
