# Generated by Django 4.2.18 on 2025-01-29 15:16

from django.db import migrations
import uuid


def generate_uuid(apps, schema_editor):
    Organisation = apps.get_model("apply_for_a_licence", "Organisation")
    Individual = apps.get_model("apply_for_a_licence", "Individual")
    for row in Organisation.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

    for row in Individual.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0012_alter_organisation_options_historicalindividual_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop),
    ]
