# Generated by Django 4.2.20 on 2025-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0012_document_temp_file_historicaldocument_temp_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="submitted_form",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="submitted_form",
            field=models.BooleanField(default=False),
        ),
    ]
