# Generated by Django 4.2.18 on 2025-01-29 14:22

from django.db import migrations, models
import uuid


def generate_uuid(apps, schema_editor):
    # Generate unique uuid for existing rows
    Organisation = apps.get_model("apply_for_a_licence", "Organisation")
    Individual = apps.get_model("apply_for_a_licence", "Individual")
    for row in Organisation.objects.all():
        row.uuid = uuid.uuid4
        row.save()
    for row in Individual.objects.all():
        row.uuid = uuid.uuid4
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0012_alter_organisation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalindividual",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="individual",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
