# Generated by Django 4.2.18 on 2025-01-29 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0012_alter_organisation_options_historicalindividual_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalindividual",
            name="id",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="id",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="id",
        ),
        migrations.AlterField(
            model_name="historicalindividual",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.UUID("a56b452a-5597-48c8-89b4-3804fafaf29a"), editable=False),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.UUID("55662afd-01eb-4edd-8957-3e783161a2b1"), editable=False),
        ),
        migrations.AlterField(
            model_name="individual",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("a56b452a-5597-48c8-89b4-3804fafaf29a"), editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("55662afd-01eb-4edd-8957-3e783161a2b1"), editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
