# Generated by Django 4.2.18 on 2025-01-23 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0012_historicalorganisation_business_registered_on_companies_house_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisation",
            name="uuid_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="uuid_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
