# Generated by Django 4.2.20 on 2025-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0013_historicallicence_submitted_documents_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallicence",
            name="submitted_documents_form",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="submitted_documents_form",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
