# Generated by Django 4.2.18 on 2025-01-29 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0013_historicalindividual_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalindividual",
            name="id",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="id",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="id",
        ),
        migrations.AlterField(
            model_name="individual",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
