# Generated by Django 4.2.18 on 2025-01-29 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0014_remove_historicalindividual_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalindividual",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="historicalorganisation",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="uuid",
        ),
        migrations.AddField(
            model_name="individual",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
