# Generated by Django 4.2.18 on 2025-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0015_rename_uuid_id_historicalorganisation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisation",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
