# Generated by Django 4.2.18 on 2025-01-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0015_remove_historicalindividual_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalindividual",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="historicalorganisation",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="individual",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="organisation",
            old_name="uuid",
            new_name="id",
        ),
    ]
