# Generated by Django 4.2.18 on 2025-01-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0016_alter_historicalorganisation_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ["created_at"]},
        ),
    ]
