# Generated by Django 4.2.18 on 2025-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0017_alter_historicalindividual_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallicence",
            name="service_activities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="service_activities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
