# Generated by Django 4.2.18 on 2025-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0020_historicalindividual_where_is_the_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalindividual",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="where_is_the_address",
            field=models.CharField(choices=[("outside-uk", "Outside the UK"), ("in-uk", "In the UK")], max_length=20, null=True),
        ),
    ]
