# Generated by Django 4.2.18 on 2025-02-04 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0021_alter_historicalindividual_where_is_the_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallicence",
            name="regimes",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name="historicallicence",
            name="service_activities",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicallicence",
            name="submitter_reference",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="relationship_provider",
            field=models.TextField(db_comment="what is the relationship between the provider and the recipient?", null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="regimes",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name="licence",
            name="service_activities",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="submitter_reference",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="relationship_provider",
            field=models.TextField(db_comment="what is the relationship between the provider and the recipient?", null=True),
        ),
    ]
