# Generated by Django 4.2.19 on 2025-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_for_a_licence", "0024_historicalindividual_is_applicant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalindividual",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="individual",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
        migrations.AddField(
            model_name="organisation",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("complete", "Complete")], default="draft", max_length=10),
        ),
    ]
