# Generated by Django 4.2.16 on 2024-11-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackitem",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeedbackitem",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
